version: '3.1'

services:

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

        #  db-init:
        #    build:
        #      context: .
        #      dockerfile: Dockerfile.init
        #    depends_on:
        #      - db
        #    environment:
        #      POSTGRES_USER: user
        #      POSTGRES_PASSWORD: password
        #      POSTGRES_DB: newsletter
        #      POSTGRES_PORT: 5432
        #      POSTGRES_HOST: 0.0.0.0
